/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    events: Event;
    testimonials: Testimonial;
    'financial-reports': FinancialReport;
    'financial-highlights': FinancialHighlight;
    'mission-cards': MissionCard;
    'values-items': ValuesItem;
    goals: Goal;
    'hero-goals': HeroGoal;
    'nav-items': NavItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'financial-reports': FinancialReportsSelect<false> | FinancialReportsSelect<true>;
    'financial-highlights': FinancialHighlightsSelect<false> | FinancialHighlightsSelect<true>;
    'mission-cards': MissionCardsSelect<false> | MissionCardsSelect<true>;
    'values-items': ValuesItemsSelect<false> | ValuesItemsSelect<true>;
    goals: GoalsSelect<false> | GoalsSelect<true>;
    'hero-goals': HeroGoalsSelect<false> | HeroGoalsSelect<true>;
    'nav-items': NavItemsSelect<false> | NavItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, lowercase-with-dashes. Page serves at mnquietvalor.com/<slug>/. Reserved: about, events, testimonials, financials, gallery, admin
   */
  slug: string;
  /**
   * Use Preview (top right) to see a draft on the real site
   */
  status: 'draft' | 'published';
  subtitle?: string | null;
  /**
   * Optional banner image
   */
  hero_image?: (number | null) | Media;
  /**
   * Legacy media filename
   */
  image_url?: string | null;
  /**
   * Build the page from sections — drag to reorder
   */
  layout: (
    | {
        text: string;
        size?: ('large' | 'small') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heading';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'text';
      }
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        label: string;
        /**
         * Link, e.g. https://… or mailto:…
         */
        url: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'button';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'divider';
      }
  )[];
  html?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL id, lowercase-with-dashes, e.g. spring-fundraiser
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * YYYY-MM-DD
   */
  date?: string | null;
  /**
   * YYYY-MM-DD (optional)
   */
  end_date?: string | null;
  /**
   * e.g. 6:00 PM
   */
  time_start?: string | null;
  time_end?: string | null;
  location?: string | null;
  /**
   * Short summary shown on cards
   */
  description?: string | null;
  /**
   * Full details shown on the event
   */
  body?: string | null;
  /**
   * Event image (preferred)
   */
  image?: (number | null) | Media;
  /**
   * Legacy media filename — leave empty for new events
   */
  image_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * e.g. U.S. Army Veteran
   */
  role?: string | null;
  quote: string;
  status: 'draft' | 'published';
  /**
   * Show on home page (first 3)
   */
  featured?: boolean | null;
  image?: (number | null) | Media;
  /**
   * Legacy media filename
   */
  image_url?: string | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-reports".
 */
export interface FinancialReport {
  id: number;
  title: string;
  /**
   * e.g. FY 2026
   */
  period?: string | null;
  description?: string | null;
  status: 'draft' | 'published';
  /**
   * PDF report (preferred)
   */
  file?: (number | null) | Media;
  /**
   * Legacy file path
   */
  file_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-highlights".
 */
export interface FinancialHighlight {
  id: number;
  label: string;
  /**
   * e.g. $25,000
   */
  value: string;
  description?: string | null;
  sort_order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-cards".
 */
export interface MissionCard {
  id: number;
  title: string;
  body: string;
  /**
   * Lower numbers appear first
   */
  sort_order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values-items".
 */
export interface ValuesItem {
  id: number;
  title: string;
  description: string;
  /**
   * Lower numbers appear first
   */
  sort_order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goals".
 */
export interface Goal {
  id: number;
  /**
   * Display number, e.g. 01
   */
  number: string;
  title: string;
  description: string;
  /**
   * Lower numbers appear first
   */
  sort_order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-goals".
 */
export interface HeroGoal {
  id: number;
  text: string;
  /**
   * Lower numbers appear first
   */
  sort_order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-items".
 */
export interface NavItem {
  id: number;
  label: string;
  /**
   * e.g. /about/ or /#contact
   */
  url: string;
  visible?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sort_order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'financial-reports';
        value: number | FinancialReport;
      } | null)
    | ({
        relationTo: 'financial-highlights';
        value: number | FinancialHighlight;
      } | null)
    | ({
        relationTo: 'mission-cards';
        value: number | MissionCard;
      } | null)
    | ({
        relationTo: 'values-items';
        value: number | ValuesItem;
      } | null)
    | ({
        relationTo: 'goals';
        value: number | Goal;
      } | null)
    | ({
        relationTo: 'hero-goals';
        value: number | HeroGoal;
      } | null)
    | ({
        relationTo: 'nav-items';
        value: number | NavItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  subtitle?: T;
  hero_image?: T;
  image_url?: T;
  layout?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        button?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  html?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  date?: T;
  end_date?: T;
  time_start?: T;
  time_end?: T;
  location?: T;
  description?: T;
  body?: T;
  image?: T;
  image_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  status?: T;
  featured?: T;
  image?: T;
  image_url?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-reports_select".
 */
export interface FinancialReportsSelect<T extends boolean = true> {
  title?: T;
  period?: T;
  description?: T;
  status?: T;
  file?: T;
  file_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-highlights_select".
 */
export interface FinancialHighlightsSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  description?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-cards_select".
 */
export interface MissionCardsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values-items_select".
 */
export interface ValuesItemsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goals_select".
 */
export interface GoalsSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  description?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-goals_select".
 */
export interface HeroGoalsSelect<T extends boolean = true> {
  text?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-items_select".
 */
export interface NavItemsSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  visible?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  hero_title?: string | null;
  hero_subtitle?: string | null;
  hero_description?: string | null;
  hero_goals_heading?: string | null;
  hero_cta_text?: string | null;
  /**
   * e.g. mailto:info@mnquietvalor.com or a URL
   */
  hero_cta_link?: string | null;
  /**
   * Hero background photo (preferred)
   */
  hero_bg?: (number | null) | Media;
  /**
   * Legacy media filename — used if no photo uploaded above
   */
  hero_bg_image?: string | null;
  /**
   * Optional video embed HTML
   */
  hero_video_embed?: string | null;
  donate_text?: string | null;
  /**
   * Donation link (Clover)
   */
  donate_url?: string | null;
  mission_label?: string | null;
  mission_title?: string | null;
  values_label?: string | null;
  values_title?: string | null;
  goals_label?: string | null;
  goals_title?: string | null;
  financials_label?: string | null;
  financials_title?: string | null;
  financials_intro?: string | null;
  banner_text?: string | null;
  banner_sub?: string | null;
  contact_label?: string | null;
  contact_title?: string | null;
  contact_intro?: string | null;
  contact_address?: string | null;
  contact_phone?: string | null;
  contact_email?: string | null;
  contact_hours?: string | null;
  contact_cta_text?: string | null;
  contact_cta_link?: string | null;
  footer_copyright?: string | null;
  footer_parent_text?: string | null;
  footer_parent_name?: string | null;
  footer_parent_link?: string | null;
  about_label?: string | null;
  about_title?: string | null;
  about_intro?: string | null;
  /**
   * Optional About header image
   */
  about_img?: (number | null) | Media;
  /**
   * Legacy media filename
   */
  about_image?: string | null;
  about_mission_title?: string | null;
  about_mission_text?: string | null;
  about_governance_title?: string | null;
  about_governance_text?: string | null;
  about_commitment_title?: string | null;
  about_commitment_text?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  hero_title?: T;
  hero_subtitle?: T;
  hero_description?: T;
  hero_goals_heading?: T;
  hero_cta_text?: T;
  hero_cta_link?: T;
  hero_bg?: T;
  hero_bg_image?: T;
  hero_video_embed?: T;
  donate_text?: T;
  donate_url?: T;
  mission_label?: T;
  mission_title?: T;
  values_label?: T;
  values_title?: T;
  goals_label?: T;
  goals_title?: T;
  financials_label?: T;
  financials_title?: T;
  financials_intro?: T;
  banner_text?: T;
  banner_sub?: T;
  contact_label?: T;
  contact_title?: T;
  contact_intro?: T;
  contact_address?: T;
  contact_phone?: T;
  contact_email?: T;
  contact_hours?: T;
  contact_cta_text?: T;
  contact_cta_link?: T;
  footer_copyright?: T;
  footer_parent_text?: T;
  footer_parent_name?: T;
  footer_parent_link?: T;
  about_label?: T;
  about_title?: T;
  about_intro?: T;
  about_img?: T;
  about_image?: T;
  about_mission_title?: T;
  about_mission_text?: T;
  about_governance_title?: T;
  about_governance_text?: T;
  about_commitment_title?: T;
  about_commitment_text?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}